services:
  mongo:
    image: mongo:7
    container_name: scraping-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: scraping

  ner:
    build: ./packages/ner-service
    container_name: scraping-ner
    ports:
      - "8001:8001"

volumes:
  mongo-data:
